name: E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      browsers:
        description: 'Browsers to test on'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - all

jobs:
  test:
    name: 'Tests on ${{ matrix.os }} with ${{ matrix.browser }}'
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        browser: [chromium]
        include:
          - os: ubuntu-latest
            browser: chromium
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install --with-deps ${{ matrix.browser }}
    
    - name: Run Playwright tests
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          # Run smoke tests for PRs
          npx playwright test --project=${{ matrix.browser }} --grep "@smoke"
        else
          # Run full regression for main branch
          npx playwright test --project=${{ matrix.browser }}
        fi
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.os }}-${{ matrix.browser }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30
        
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots-${{ matrix.os }}-${{ matrix.browser }}
        path: test-results
        retention-days: 7

  report:
    name: 'Generate Test Report'
    needs: test
    if: always()
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Display structure of downloaded files
      run: ls -R artifacts
      shell: bash
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate combined report
      run: |
        mkdir -p playwright-report
        find artifacts -name "*.zip" -exec unzip -o {} -d playwright-report \;
      shell: bash
        
    - name: Deploy report to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        publish_branch: gh-pages
        keep_files: true
